#!/bin/bash 
if [ -z "$1" ]                                          
then                                                    
    echo "Usage: MakeGitlabRelease.sh <push token> <Gitlab api url> <project id> <tag> <file.md> [-b]"
    echo " Options:"
    echo "  -b Write beta instead of official in relaease note title"
else                                                                                                                          
    push_token=$1
    api=$2
    proj=$3
    tag=$4
    file=$5

    if [ "$6" == "-b" ]
    then
	version_type="Beta"
    else
	version_type="Official"
    fi
    
    curl --request POST --header "PRIVATE-TOKEN: ${push_token}" --header "Content-Type: application/json" \
	--data '{ "name": "'"$version_type"' version: '"$tag"'", "tag_name": "'"$tag"'", "description": "'"`sed -e ':a' -e 'N' -e '$!ba' -e 's/\n/\\\\n/g' $file`"' \n\n ---\n Release note automatically generated by **Hog**."}' \
	$api/projects/${proj}/${mr}/releases
fi
