#!/bin/bash
#   Copyright 2018-2020 The University of Birmingham
#
#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.

if [ -z "$1" ]
then
    echo "Usage: MakeGitlabRelease.sh <push token> <Gitlab api url> <project id> <tag> <file.md> [-b]"
    echo " Options:"
    echo "  -b Write beta instead of official in release note title"
else
    push_token=$1
    api=$2
    proj=$3
    tag=$4
    file=$5

    if [ "$6" == "-b" ]
    then
	version_type="Beta"
    else
	version_type="Official"
    fi

    curl --request POST --header "PRIVATE-TOKEN: ${push_token}" --header "Content-Type: application/json" \
	--data '{ "name": "'"$version_type"' version: '"$tag"'", "tag_name": "'"$tag"'", "description": "'"`sed -e ':a' -e 'N' -e '$!ba' -e 's/\n/\\\\n/g' $file`"' \n\n ---\n Release note automatically generated by **Hog**."}' \
	$api/projects/${proj}/${mr}/releases
fi
