default:
      before_script:
          - export REPO=`echo $CI_PROJECT_URL | sed -e s#https://##`
          - git remote set-url origin https://hog:${HOG_PUSH_TOKEN}@$REPO
          - git config user.email "hog.cern.ch"
          - git config user.name "Hog"
          - git fetch 
          - git fetch origin $CI_COMMIT_REF_NAME
          - git checkout $CI_COMMIT_REF_NAME

stages:
      - tag
      - build
      - deploy

building:
      stage: build
      image: gitlab-registry.cern.ch/authoring/documentation/mkdocs:stable
      before_script: 
        - echo ""
      script:
        - mkdocs build --clean --site-dir public
        - cp docs/.htaccess public/
      artifacts:
        paths:
          - public
        expire_in: 1 hour
        
building-doxygen:
      stage: build
      image: gitlab-registry.cern.ch/cholm/docker-ubuntu-doxygen:stable
      before_script:
        - echo ""
      script:
        - cd doxygen
        - doxygen HOG-doxygen.cfg
      artifacts:
        paths:
          - doxygen/DOXY_DOCS
        expire_in: 1 hour
        
deploying:
      stage: deploy
      image: gitlab-registry.cern.ch/ci-tools/ci-web-deployer:latest
      only:
        - feature/documentation
      before_script:
        - echo ""
      script:
        - deploy-eos
        - CI_DOXY_OUTPUT="doxygen/DOXY_DOCS/html"
        - EOS_DOXY_PATH="eos/user/h/hog/www/test-doxy"
        - /usr/bin/xrdcp --force --recursive "$CI_DOXY_OUTPUT/" "$EOS_MGM_URL/$EOS_DOXY_PATH/" 2>&1 >/dev/null


merge-and-tag:
      stage: tag
      image: tcl2020/tcl2020:latest
      only: 
           refs:
              - merge_requests
      script:
          - "MR_PARAMETERS=`curl --header \"PRIVATE-TOKEN: ${HOG_PUSH_TOKEN}\" ${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/merge_requests/${CI_MERGE_REQUEST_IID}`"
          - ./Tcl/launchers/launch_merge_and_tag.tcl -Hog  -mr_par "$MR_PARAMETERS" -mr_id $CI_MERGE_REQUEST_IID -push $CI_COMMIT_REF_NAME

tagging:
      stage: tag
      image: tcl2020/tcl2020:latest
      only: 
          - push
          - web
      except:
          variables:
              - $CI_PIPELINE_SOURCE != "push"
              - $CI_COMMIT_REF_SLUG != "master"
      script:
          - ./Tcl/launchers/launch_merge_and_tag.tcl -Hog -merged -push $CI_COMMIT_REF_NAME
