stages:
#      - build
#      - deploy
      - tag
#building:
#      stage: build
#      image: gitlab-registry.cern.ch/authoring/documentation/mkdocs:stable
#      script:
#        - mkdocs build --clean --site-dir public
#        - cp docs/.htaccess public/
#      artifacts:
#        paths:
#          - public
#        expire_in: 1 hour
#deploying:
#      stage: deploy
#      image: gitlab-registry.cern.ch/ci-tools/ci-web-deployer:latest
#      only:
#        - feature/documentation
#      script:
#        - deploy-eos
tagging:
      stage: tag
      image: tcl2020/tcl2020:latest
      only: 
          - push
          - web
      except:
          variables:
              - $CI_PIPELINE_SOURCE != "push"
#              - $CI_COMMIT_REF_SLUG != "master"
      script:
          - export REPO=`echo $CI_PROJECT_URL | sed -e s#https://##`
          - git --version
          - which tclsh
          - git remote set-url origin https://hog:${HOG_PUSH_TOKEN}@$REPO
          - git config user.email "hog.cern.ch"
          - git config user.name "Hog"
          - git fetch 
          - git fetch origin $CI_COMMIT_REF_SLUG
          - git status
#          - git pull
          - ./Tcl/tag_repository.tcl -tclargs 0 0 1
#          - git push origin $CI_COMMIT_REF_NAME
#          - git push --tags origin $CI_COMMIT_REF_NAME
