#   Copyright 2018-2020 The University of Birmingham
#
#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.


default:
      before_script:
          - export REPO=`echo $CI_PROJECT_URL | sed -e s#https://##`
          - git remote set-url origin https://hog:${HOG_PUSH_TOKEN}@$REPO
          - git config user.email "hog.cern.ch"
          - git config user.name "Hog"
          - git fetch
          - git fetch origin $CI_COMMIT_REF_NAME
          - git checkout $CI_COMMIT_REF_NAME --

stages:
      - tag
      - build_doc
      - deploy_doc

doc:
      stage: build_doc
      image: gitlab-registry.cern.ch/authoring/documentation/mkdocs:stable
      except:
           variables:
              - $CI_COMMIT_REF_NAME =~ /^test\/.*$/i
      before_script:
        - echo ""
      script:
        - mkdocs build --clean --site-dir public
        - cp docs/.htaccess public/
      artifacts:
        paths:
          - public
        expire_in: 1 day

building-doxygen:
      stage: build_doc
      image: cern/cc7-base
      before_script:
        - echo ""
      script:
        - yum install -y doxygen krb5-workstation rsync openssh-clients xrootd-client which
        - cd doxygen
        - ./scripts/build-and-deploy.sh
      artifacts:
        paths:
          - doxygen/DOXY_DOCS
        expire_in: 1 hour

dep_doc:
      stage: deploy_doc
      image: gitlab-registry.cern.ch/ci-tools/ci-web-deployer:latest
      only:
        - feature/documentation
      before_script:
        - echo ""
      script:
        - deploy-eos


merge_and_tag:
      stage: tag
      image: tcl2020/tcl2020:latest
      only:
           refs:
              - merge_requests
      except:
           variables:
              - $CI_COMMIT_REF_NAME =~ /^test\/.*$/i
      script:
          - "MR_PARAMETERS=`curl --header \"PRIVATE-TOKEN: ${HOG_PUSH_TOKEN}\" ${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/merge_requests/${CI_MERGE_REQUEST_IID}`"
          - tclsh ./Tcl/CI/merge_and_tag.tcl -Hog  -mr_par "$MR_PARAMETERS" -mr_id $CI_MERGE_REQUEST_IID -push $CI_COMMIT_REF_NAME
          - git fetch origin refs/notes/*:refs/notes/*
          - git notes add -fm "$CI_MERGE_REQUEST_IID"
          - git push origin refs/notes/*
          - ./Other/Changelog.sh $CI_MERGE_REQUEST_TARGET_BRANCH_NAME > changelog.md
      artifacts:
        name: changelog
        paths:
          - changelog.md
        expire_in: 1 month

tagging:
      stage: tag
      image: tcl2020/tcl2020:latest
      only:
          - push
          - web
      except:
          variables:
              - $CI_PIPELINE_SOURCE != "push"
              - $CI_COMMIT_REF_SLUG != "develop"
      script:
          - tclsh ./Tcl/CI/merge_and_tag.tcl -Hog -merged -push $CI_COMMIT_REF_NAME

create_release_note:
        stage: tag
        image: tcl2020/tcl2020:latest
        only:
          refs:
            - tags
          variables:
            - $CI_COMMIT_TAG =~ /^v.*$/

        script:
          - git fetch origin refs/notes/*:refs/notes/*
          - MR=`git notes show`
          - ./Other/GetGitlabArtifact.sh $HOG_PUSH_TOKEN $CI_API_V4_URL $CI_PROJECT_ID $MR changelog.md merge_and_tag > note.md
          - ./Other/MakeGitlabRelease.sh $HOG_PUSH_TOKEN $CI_API_V4_URL $CI_PROJECT_ID $CI_COMMIT_TAG note.md -b
