site_name: Hog user manual
site_description: HDL on git user manual 
site_author: CERN Authoring
site_url: http://cern.ch/hog-user-manual
repo_name: GitLab
repo_url: https://gitlab.cern.ch/hog/Hog
theme:
      name: material
      nav:
        - 'Introduction': index.md
        - 'Getting Started': 01-Getting-Started
        - 'Maintainer Manual': 02-Maintainer-Manual
        - 'Contributing':  03-Contributing
        - 'MkDocs official documentation': https://www.mkdocs.org/
      logo: 'assets/images/favicon.png'
markdown_extensions:
  - footnotes
