site_name: Hog user manual
site_description: HDL on git user manual 
site_author: CERN Authoring
site_url: http://cern.ch/hog-user-manual
repo_name: GitLab
repo_url: https://gitlab.cern.ch/hog/Hog

nav:
- Introduction: 'index.md'

- 'Getting Started':
  - 01-Getting-Started/01-existingProjects.md
  - 01-Getting-Started/02-setupNewHogProject.md
  - 01-Getting-Started/03-convert-project.md
  - 01-Getting-Started/04-update-hog.md

- 'Hog User Manual':
  - 'Using Hog Locally':
    - 02-User-Manual/01-Hog-local/01-supported-tools.md
    - 02-User-Manual/01-Hog-local/02-available-templates.md
    - 02-User-Manual/01-Hog-local/03-Hog-generics.md
    - 02-User-Manual/01-Hog-local/04-Project-Tcl.md
    - 02-User-Manual/01-Hog-local/05-List-files.md
    - 02-User-Manual/01-Hog-local/6-IPbus-support.md
  - 'Hog Continuous Integration':
    - 02-User-Manual/02-Hog-CI/01-gitlab-repository-setup.md
    - 02-User-Manual/02-Hog-CI/02-setup-CI.md
    - 02-User-Manual/02-Hog-CI/03-HOG-CI-stages.md
    - 02-User-Manual/02-Hog-CI/04-Virtual-Machines.md

- 'Contributing to Hog':
  - 03-Improving-Debugging/01-reporting-bug.md
  - 03-Improving-Debugging/02-contributing.md 

- 'MkDocs official documentation': https://www.mkdocs.org/


markdown_extensions:
  - footnotes
theme:
      name: material
      logo: 'custom/assets/images/white.png'
      custom_dir: docs/custom/
      features:
        - tabs

extra_css:
    - extra.css

#plugins:
#    - search
#    - pdf-export:
#        media_type: print
#        combined: true

