name: Hog

on:
  workflow_call:
    inputs:
      PROJECT_NAME:
        required: true
        type: string

jobs:
  build:
    runs-on: self-hosted
    env:
      HOG_PATH: /opt/Xilinx/Vivado/2020.2/bin
    steps:
      - uses: actions/checkout@v2
        with: 
          fetch-depth: 0
      - uses: webfactory/ssh-agent@v0.5.4
        with:
            ssh-private-key: ${{ secrets.SUBMODULE_CONTENT_PULL_KEY }}
      - name: Hog
        run: |
              git submodule init
              git submodule update --remote
              export PATH=${HOG_PATH}:$PATH
              git fetch -p
              git --version
              cd Hog/ && git fetch -p
              cd ..
              ./Hog/LaunchWorkflow.sh ${{ inputs.PROJECT_NAME }}
      - name: Archive production artifacts
        uses: actions/upload-artifact@v3
        with:
          name: Create artifacts
          path: |
            Projects