## @brief Write a cocotb python template to build the selected project with an empty test
# @param[in] project_name The name of the project to build
# @param[in] repo_path    The main path of the repository

proc WriteCocoTbTemplate {project_name repo_path lib_path {ext_path ""}} {
    # Procedure body
    cd $repo_path
    Msg Info "Creating cocotb library build script for project $project_name..."
    set proj_list_dir $repo_path/Top/$project_name/list
    set project [file tail $project_name]
    lassign [GetHogFiles -ext_path $ext_path \
        -list_files ".src,.ext" $proj_list_dir $repo_path]\
        listLibraries listProperties listSrcSets

    set compile_order [Hierarchy $listProperties $listLibraries $repo_path "" 1 "" "" "" 0 0 1]
    set py_file [open "cocotb_$project.py" w]
    set valid_extensions ".vhd .vhdl .v .sv .svh .vh"

    puts $py_file "#!/usr/bin/env python3"
    puts $py_file "\"\"\"Auto-generated by Hog COCOTB command for project $project.\"\"\""
    puts $py_file ""
    puts $py_file "import argparse"
    puts $py_file "from pathlib import Path"
    puts $py_file "import cocotb"
    puts $py_file "from cocotb_tools.runner import get_runner"
    puts $py_file ""
    puts $py_file "REPO_ROOT = Path(__file__).resolve().parent"
    puts $py_file ""
    puts $py_file ""
    puts $py_file "@cocotb.test()"
    puts $py_file "async def test_placeholder(dut):"
    puts $py_file "    \"\"\"Placeholder test -- replace with actual test logic.\"\"\""
    puts $py_file "    pass"
    puts $py_file ""
    puts $py_file ""
    puts $py_file "def build_libs(sim: str, build_dir: str) -> None:"
    puts $py_file "    runner = get_runner(sim)"
    puts $py_file "    build_path = Path(build_dir)"
    puts $py_file ""

    # Collect unique directories containing .svh/.vh header files so we can
    # emit +incdir+ flags for every SV/SVH compilation unit.
    set svh_dirs [list]
    foreach {f _} $compile_order {
        set ext [file extension $f]
        if {$ext eq ".svh" || $ext eq ".vh"} {
            set dir [file dirname $f]
            if {[lsearch -exact $svh_dirs $dir] == -1} {
                lappend svh_dirs $dir
            }
        }
    }

    foreach {f l} $compile_order {
        set lib_name $l
        set ext [file extension $f]
        set rel [Relative $repo_path $f]
        if {![IsInList $ext $valid_extensions] } {
            continue
        }

        puts $py_file "    runner.build("
        puts $py_file "        hdl_library=\"$lib_name\","
        puts $py_file "        sources=\["
        puts $py_file "            REPO_ROOT / \"$rel\","
        puts $py_file "        \],"
        puts $py_file "        build_dir=build_path,"
        if {$ext == ".vhd" || $ext == ".vhdl"} {
            puts $py_file "        build_args = \[ \"-2008\","
            if {$lib_path != ""} {
                puts $py_file "\"-modelsimini\", \"$lib_path/modelsim.ini\""
            }
            puts $py_file "\],"
        } elseif {$ext == ".sv" || $ext == ".svh" || $ext == ".v" || $ext == ".vh"} {
            if {[llength $svh_dirs] > 0} {
                puts $py_file "        build_args = \["
                foreach dir $svh_dirs {
                    set rel_dir [Relative $repo_path $dir]
                    puts $py_file "            \"+incdir+\" + str(REPO_ROOT / \"$rel_dir\"),"
                }
                puts $py_file "        \],"
            }
        }
        puts $py_file "        always=True,"
        puts $py_file "    )"
        puts $py_file ""
    }

    puts $py_file ""
    puts $py_file "def run_test(sim: str, build_dir: str, toplevel: str) -> None:"
    puts $py_file "    runner = get_runner(sim)"
    puts $py_file "    runner.test("
    puts $py_file "        hdl_toplevel=toplevel,"
    puts $py_file "        test_module=Path(__file__).stem,"
    puts $py_file "        build_dir=build_dir,"
    puts $py_file "    )"
    puts $py_file ""
    puts $py_file ""
    puts $py_file "if __name__ == \"__main__\":"
    puts $py_file "    parser = argparse.ArgumentParser()"
    puts $py_file "    parser.add_argument(\"--sim\", default=\"questa\")"
    puts $py_file "    parser.add_argument(\"--build-dir\", default=\"sim_build\")"
    puts $py_file "    parser.add_argument(\"--toplevel\", default=\"<toplevel>\")"
    puts $py_file "    args = parser.parse_args()"
    puts $py_file "    build_libs(args.sim, args.build_dir)"
    puts $py_file "    run_test(args.sim, args.build_dir, args.toplevel)"

    close $py_file
    Msg Info "cocotb Python script created: cocotb_$project.py"
    Msg Info "Run it with: python cocotb_$project.py --sim questa --toplevel <your_toplevel>"
}