include:
    - project: 'hog/Hog'
      file: '/gitlab-ci.yml'
      ref: 'v0.2.1' # if not specified would use the master branch

#################### example ###########################
### Change 'example' with your project name

create_project:example:
    extends: .create_project
    variables:
      extends: .vars
      PROJECT_NAME: example

simulate_project:example:
    extends: .simulate_project
    variables:
      extends: .vars
      PROJECT_NAME: example
      SIMULATOR: vivadosim

synthesise_ips:example:
    extends: .synthesise_ips
    variables:
      extends: .vars
      PROJECT_NAME: example
    dependencies:
        - create_project:example

synthesise_project:example:
    extends: .synthesise_project
    variables:
      extends: .vars
      PROJECT_NAME: example
    dependencies:
        - synthesise_ips:example

implement_project:example:
    extends: .implement_project
    variables:
      extends: .vars
      PROJECT_NAME: example
      HOG_NO_BITSTREAM : 1
    dependencies:
      - synthesise_project:example