

# for project hog.conf:
[sigasi]
TOP_LEVEL="netfelix.netfelix_vp1552.example_project"

# for repo repo.conf
[sigasi]
## Sigasi format options
# sets size of tabs
TAB_WIDTH=4

# Sets case of keywords. Valid options are uppercase, lowercase, ignore
KEYWORDS="lowercase"

# additional options are available. Leave commented if unwanted
# If set sigasi will not remove excess blank lines
# PRESERVE_NEWLINES=1

# if set tabs will be used instead of spaces
# TABS=1

# if set no code alignement will be done
# NO_ALIGN=1

# Can specify a VHDL version. Valid options 93, 2002, 2008, or 2019
# VHDL_VERSION=2008

# set directories to ignore. Ideal if project is using submodules. Comma separated list
# IGNORE_DIR="submodule, rtl/config"

## Sigasi verify options
# library database is treated as comma separated list
# Where the sigasi extracted libraries are
LIBRARY_DATABASE="~/.config/sigasi"

# location of report file. File extension not required
REPORT_OUTFILE="./sigasi_report.txt"

# report format
REPORT_FORMAT="plain"
# Available options
    # plain
    # json
    # sonarqube
    # warnings-ng

# Set following to anything to provide absolute paths in the reports
# REPORT_ABSOLUTE=0

# Set following to anything to report suppressed errors/warnings
# REPORT_SUPPRESSED="true"

# Set following if a lint failure is wanted. Recommend to set on error
# if not set, verify will always pass
FAIL="error"
    # error
    # warning
    # info

## Sigasi document options
# Reuses LIBRARY_DATABASE from verify options
# LIBRARY_DATABASE="~/.config/sigasi"

# set output doc directory
# DOC_DIR="./sigasi-docs"

# set node limit for diagrams
DIAGRAM_NODE_LIMIT=2500

# set design units per pages. Leave unset for a single page output
DESIGN_UNITS_PER_PAGE="25"

# set to define how diagrams are stored
DIAGRAMS="LINKED"
    # EMBEDDED
    # LINKED
    # NONE

# Recommend - but not required. Sets top level for the documentation report
# if different top levels are required for projects in the same repository this can be put inside
# the project hog.conf instead.
# TOP_LEVEL uses '.' to separate levels: work.entity.architecture
TOP_LEVEL="netfelix.netfelix_vp1552.example_project"